food/food/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
]

food/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    #home page at recipes/
    path('', views.IndexView.as_view(), name='index'),
    path('load_recipes', views.load_recipes, name='load_recipes'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search/results', views.ResultsView.as_view(), name='results'),
]

food/recipes/models.py
import datetime
import json
import re

from django.db import models
from django.utils import timezone


# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class RecipeManager(models.Manager):
    def create_recipe(self, data):
        
        if data.get("image_link") == None:
            image_url = {
                            "Dessert": "/recipes/dessert.png",
                            "Drink": "/recipes/drink.png",
                            "Side": "/recipes/entree_vegetarian.png",
                            "Salad": "/recipes/salad.png",
                            "Soup": "/recipes/soup.png",
                         }
            if data.get("type") == "Entree":
                if data.get("vegetarian") == 'TRUE':
                    image_url["Entree"] = "/recipes/entree_vegetarian.png"
                elif "Fish" in data.get("tags").split(", "):
                    image_url["Entree"] = "/recipes/entree_fish.png"
                else:
                    image_url["Entree"] = "/recipes/entree_meat.png"
            data["image_link"] = image_url[data.get("type")]

        new_recipe, created = self.get_or_create(
            name = data.get("name"),
            link = data.get("link",""),
            image_link = data.get("image_link",""),
            type = data.get("type"),
            cook_time = int(data.get("cook_time",0)),
            prep_time = int(data.get("prep_time",0)),
            freezes_well = data.get("freezes_well") == "TRUE",
            vegetarian = data.get("vegetarian") == "TRUE",
            could_be_vegetarian = data.get("could_be_vegetarian?") == "TRUE",
            spicy = data.get("spicy?") == "TRUE",
            could_be_spicy = data.get("could_be_spicy?") == "TRUE",
            tags = json.dumps(data.get("tags","").split(", ")),
            times_made = int(data.get("times_made",0)),
            last_time_made = data.get("last_time_made",None)
        )

        if created:
            genres = data.get("genres","").split(", ")
            for genre in genres:
                recipe_genre, created = Genre.objects.get_or_create(name = genre)
                new_recipe.genres.add(recipe_genre)
        return new_recipe

class Recipe(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField(max_length=2083, blank = True)
    image_link = models.URLField(max_length=2083, blank = True)

    genres = models.ManyToManyField(Genre)
    type = models.CharField(max_length = 200)

    cook_time = models.IntegerField()
    prep_time = models.IntegerField()

    freezes_well = models.BooleanField(default = False)
    vegetarian = models.BooleanField(default = False)
    could_be_vegetarian = models.BooleanField(default = False)
    spicy = models.BooleanField(default = False)
    could_be_spicy = models.BooleanField(default = False)

    # tags will be a list, it will need
    # to be decoded (and encodeded?) using json
    tags = models.CharField(max_length = 500, blank = True)

    times_made = models.IntegerField(default = 0)
    last_time_made = models.DateField(null = True, blank = True)

    objects = RecipeManager()

    def __str__(self):
        return self.name

    def convert_cook_time(self):
        cook_time_conversion = {
            0: "No cooking required",
            1: "1 to 15 minutes",
            2: "15 to 30 minutes",
            3: "30 to 45 minutes",
            4: "45 to 75 minutes",
            5: "1 to 2 hours",
            6: "Slow-cooker recipe, anywhere from 2 to 12 hours"
        }
        return cook_time_conversion[self.cook_time]

    def convert_prep_time(self):
        prep_time_conversion = {
            1: "1 to 5 minutes",
            2: "5 to 15 minutes",
            3: "15 to 30 minutes",
            4: "30 to 45 minutes",
            5: "45 to 75 minutes",
            6: "Requires advanced preparation, like marinating for several hours or soaking overnight."
        }
        return prep_time_conversion[self.prep_time]

    def convert_genres(self):
        all_genres = ""
        genres = self.genres.all()
        for counter, genre in enumerate(genres):
            all_genres += genre.name
            if not counter == len(genres)-1:
                all_genres += ", "
        return all_genres

    def get_tags_as_list(self):
        all_tags = []
        if self.vegetarian:
            all_tags.append("Vegetarian")
        elif self.could_be_vegetarian:
            all_tags.append("Vegetarian Option")

        if self.spicy:
            all_tags.append("Spicy")
        elif self.could_be_spicy:
            all_tags.append("Spicy Option")

        if self.tags != "":
            tags = json.loads(self.tags)
            all_tags += tags

        return all_tags

    def get_tags_as_string(self):
        all_tags = self.get_tags_as_list()
        tags_string = ""
        for counter, tag in enumerate(all_tags):
            tags_string += tag
            if not counter == len(all_tags)-1:
                tags_string += ", "
        return tags_string

    def update_times_made(self):
        self.times_made += 1
        self.last_time_made = timezone.now().date()
        self.save()

    def is_static(self):
        if re.search('^/recipes/', self.image_link) == None:
            return False
        return True

food/recipes/views.py
import requests
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Recipe, Genre

class IndexView(generic.ListView):
    model = Recipe
    context_object_name = 'recipes_list'
    template_name = 'recipes/index.html'

class DetailView(generic.DetailView):
    model = Recipe
    template_name = 'recipes/details.html'

class SearchView(generic.ListView):
    model = Genre
    context_object_name = 'genres_list'
    template_name = 'recipes/search.html'

class ResultsView(generic.ListView):
    template_name = 'recipes/index.html'
    context_object_name = 'recipes_list'

    def get_queryset(self):
        """ filter results by query params given by search """
        filtered = Recipe.objects.filter(
            cook_time__gte=self.request.GET.get('cook_time_min', 0),
            cook_time__lte=self.request.GET.get('cook_time_max', 6),
            prep_time__gte=self.request.GET.get('prep_time_min', 0),
            prep_time__lte=self.request.GET.get('prep_time_max', 6)
        )

        if self.request.GET.getlist('types'):
            filtered = filtered.filter(
                type__in=self.request.GET.getlist('types')
            )
        if self.request.GET.getlist('genres'):
            filtered = filtered.filter(
                genres__name__in=self.request.GET.getlist('genres')
            )
        if self.request.GET.get('freeze'):
            filtered = filtered.filter(freezes_well=True)

        if self.request.GET.get('vegetarian'):
            veg = self.request.GET.get('vegetarian')

            if veg == "yes":
                filtered = filtered.filter(vegetarian=True)
            elif veg == "options":
                filtered = filtered.filter(Q(vegetarian=True) | Q(could_be_vegetarian=True))
            elif veg == "no":
                filtered = filtered.filter(vegetarian=False)

        if self.request.GET.get('spicy'):
            spicy = self.request.GET.get('spicy')

            if spicy == "yes":
                filtered = filtered.filter(spicy=True)
            elif spicy == "options":
                filtered = filtered.filter(Q(spicy=False) & Q(could_be_spicy=True))
            elif spicy == "no":
                filtered = filtered.filter(spicy=False)

        return filtered

def load_recipes(request):
    if request.method == "GET":
        context = {"recipes_not_loaded": True}
        return render(request, 'recipes/load_recipes.html', context)
    if request.method == "POST":
        # call published google sheets to gather data
        from_sheets = requests.get("https://spreadsheets.google.com/feeds/cells/1MLqtrZ9gQHGK02wAtxmMogOmrhqRsUsAE5eXT1IAzOE/od6/public/values?alt=json")
        recipes_raw = from_sheets.json()
        recipe_cell_data = []
        # initial parse of data into an array, results in an array of dictonaries with row, column and cell text values
        for recipe in recipes_raw["feed"]["entry"]:
            recipe_cell_data.append(recipe["gs$cell"])
        # creating 2 empty dictonaries for header assignment and model data collection. Counter starts at 2 because row 1 is the header.
        assignment = {}
        recipe_model_data = {}
        recipe_counter = 2
        for recipe_cell in recipe_cell_data:
            if int(recipe_cell["row"]) == recipe_counter:
                # iterate through a single row of spreadsheet data, and put that data into a dictonary with key based on headers and the value based on the spreadsheet cell.
                recipe_model_data[assignment[recipe_cell["col"]]] = recipe_cell["$t"].strip()
            elif int(recipe_cell["row"]) == recipe_counter + 1:
                # after the row has finished parsing, create the model based on the data from the above row, reset the accumluator and continue to iterate.
                Recipe.objects.create_recipe(recipe_model_data)
                recipe_counter += 1
                recipe_model_data = {}
                recipe_model_data[assignment[recipe_cell["col"]]] = recipe_cell["$t"].strip()
            elif recipe_cell["row"] == "1":
                # iterate through first rows of cells and assign a key corrisponding to the column number and a value equal to the text.
                assignment[recipe_cell["col"]] = recipe_cell["$t"].strip().lower().replace(" ", "_")
        # pass all newly created objects to the template
        context = {"new_recipes": Recipe.objects.all()}
        return render(request, 'recipes/load_recipes.html', context)

food/recipes/templates/recipes/details.html
{% extends 'navbar.html' %}
{% load static%}
{% block content %}
<h1> {{recipe.name}} </h1>
<h2>{{recipe.type}}</h2>
<h2> {{recipe.convert_genres}} </h2>

<h3>Cook Time: {{ recipe.convert_cook_time }}</h3>

<h3>Prep Time: {{ recipe.convert_prep_time }}</h3>
{%if recipe.link%}
  <a href="{{recipe.link}}">Find the recipe here!</a>
{%endif%}

{%if recipe.is_static%}
  <img src="{% static recipe.image_link %}" alt="A default image of a {{recipe.type}}">
{%else%}
  <img src="{{recipe.image_link}}" alt="A picture of {{recipe.name}}">
{%endif%}

<p>
  {%if recipe.get_tags_as_string%}
    Tags: {{recipe.get_tags_as_string}}
  {%endif%}
</p>

<p>
  {%if recipe.times_made == 0%}
    This recipe hasn't been made yet! Why not give it a try?
  {%else%}
    This recipe has been made {{recipe.times_made}} time{{ recipe.times_made|pluralize }}. <br>
    It was last made {{recipe.last_time_made}}
  {%endif%}
</p>
{% endblock %}
<!-- Add functionality for incrementing the times_made and the most recent date
currently broken, fix later!

<button type="button" name="made_it" id="made_this">I made this!</button>

<script type="text/javascript">
  var button = document.getElementById("made_this");
  button.addEventListener("click", ()=>{
    button.disabled = true;
    button.innerHTML = "Delicious!";
    put times made function here maybe?;
  } )
</script>
-->

food/recipes/templates/recipes/index.html
{% extends 'navbar.html' %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/index_style.css' %}">

    <title>K+A Recipes</title>
    {% endblock %}
  </head>
  <body>
  {% block content %}
  <div class="container">
    <div class="row">
      <h1>Recipes</h1>
    </div>

    {%for recipe in recipes_list%}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% endif %}
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
        <div class="mainflip">
          <a href="{% url 'recipes:detail' recipe.id %}">
          <div class="frontside">
            <div class="card">
              <div class="card-image-container">
                {%if recipe.is_static%}
                  <img class="card-img-top card-image" src="{% static recipe.image_link %}" alt="A default image of a {{recipe.type}}">
                {%else%}
                  <img class="card-img-top card-image" src="{{recipe.image_link}}" alt="A picture of {{recipe.name}}">
                {%endif%}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{recipe.name}}</h5>
                <h6 class="card-text">{{recipe.convert_genres}}</h6>
              </div>
            </div>
          </div>
          </a>
          <a href="{% url 'recipes:detail' recipe.id %}">
          <div class="backside">
            <div class="card">
              <div class="card-header">
                {{recipe.name}}
              </div>
              <div class="card-body">
                <p class="card-text">Cook Time: {{recipe.convert_cook_time}}</p>
                <p class="card-text">Prep Time: {{recipe.convert_prep_time}}</p>
                <p class="card-text">
                {%if recipe.times_made == 0%}
                  This recipe hasn't been made yet! Why not give it a try?
                {%else%}
                  This recipe has been made {{recipe.times_made}} time{{ recipe.times_made|pluralize }}. <br>
                  It was last made {{recipe.last_time_made}}
                {%endif%}
                </p>
                {%if recipe.link %}
                <!-- line breaker causes footer overlap -->
                <p class="card-text"></p>
                <a href="{{recipe.link}}">Direct Link</a>
                {%endif%}
              </div>
              <div class="card-footer">
                {{recipe.get_tags_as_string}}
              </div>
            </div>
          </div>
          </a>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}
      </div>
    {% endif %}
    {%endfor%}
  </div>
  {% endblock %}
  </body>
</html>

food/recipes/templates/recipes/load_recipes.html
{% if recipes_not_loaded %}
  <form method="post" action={% url 'recipes:load_recipes' %}>
    {% csrf_token %}
    <input type="submit" value="Load Recipes">
  </form>
{% else %}
  {% if new_recipes %}
  <h1>Recipes Loaded!</h1>
      <ul>
      {% for recipe in new_recipes %}
          <li><a href="/recipes/{{ recipe.id }}/">{{ recipe.name }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
    <h1>Recipe Load Failure!</h1>
  {% endif %}
{% endif %}

food/recipes/templates/recipes/search.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    // code pulled from https://stackoverflow.com/questions/45517884/drop-down-menu-option-selected-based-on-url-paramater
    // Construct URL object using current browser URL
    var url = new URL(document.location);

    // Get query parameters object
    var params = url.searchParams;

    // Get values of veg and spicy
    var veg = params.get("vegetarian");
    var spicy = params.get("spicy");

    // Set default value to be shrug
    $("#vegetarian").val(shrug);
    $("#spicy").val(shrug);

    // Set query params based on value
    $("#vegetarian").val(veg);
    $("#spicy").val(spicy);
  });
</script>

<h1>Search</h1>

<form method="get" action={% url 'recipes:results'%}>
  Type: <br>
  <input type="checkbox"> Select all<br>
  <input type="checkbox" name = "types" value="Entree"> Entree <br>
  <input type="checkbox" name = "types" value="Side"> Side <br>
  <input type="checkbox" name = "types" value="Salad"> Salad <br>
  <input type="checkbox" name = "types" value="Soup"> Soup <br>
  <input type="checkbox" name = "types" value="Dessert"> Dessert <br>
  <input type="checkbox" name = "types" value="Drink"> Drink <br>
  <br>

  Genre: <br>
  <input type="checkbox"> Select all<br>
  {%for genre in genres_list%}
    <input type="checkbox" name = "genres" value="{{genre.name}}"> {{genre.name}}<br>
  {%endfor%}
  <br>

  Cook Time: <br>
  Min: <input type="number" name="cook_time_min" min = "0" max = "6" value = "0">
  Max: <input type="number" name="cook_time_max" min = "0" max = "6" value = "6">
  <br> <br>

  Prep Time: <br>
  Min: <input type="number" name="prep_time_min" min = "0" max = "6" value = "0">
  Max: <input type="number" name="prep_time_max" min = "0" max = "6" value = "6">
  <br> <br>

  Vegetarian:
  <select name="vegetarian" id='vegetarian'>
    <option value="shrug">¯\_(ツ)_/¯</option>
    <option value="yes">Yes</option>
    <option value="options">Vegetarian/Vegetarian Substitutions</option>
    <option value="no">Meat only</option>
  </select>
  <br> <br>

  Spicy:
  <select name="spicy" id=spicy>
    <option value="shrug">¯\_(ツ)_/¯</option>
    <option value="yes">Yes</option>
    <option value="options">Spicy option</option>
    <option value="no">No</option>
  </select>
  <br> <br>

  Freezes well?
  <input type="checkbox" name="freeze" value = "True">
  <br>

  <br>
  <input type="submit" value="Search">
  <input type="reset">
</form>